"""Built-in selectable catalogs for countries, periods, and figures."""

from __future__ import annotations

# (name, flag/icon) — World first (earth / global history), then modern countries.
# Empires are separate (see EMPIRES) and nest under a selected country in the Add flow.
COUNTRIES: list[tuple[str, str]] = [
    ('World', '🌍'),
    ('Afghanistan', '🇦🇫'),
    ('Albania', '🇦🇱'),
    ('Algeria', '🇩🇿'),
    ('American Samoa', '🇦🇸'),
    ('Andorra', '🇦🇩'),
    ('Angola', '🇦🇴'),
    ('Anguilla', '🇦🇮'),
    ('Antarctica', '🇦🇶'),
    ('Antigua and Barbuda', '🇦🇬'),
    ('Argentina', '🇦🇷'),
    ('Armenia', '🇦🇲'),
    ('Aruba', '🇦🇼'),
    ('Australia', '🇦🇺'),
    ('Austria', '🇦🇹'),
    ('Azerbaijan', '🇦🇿'),
    ('Bahamas', '🇧🇸'),
    ('Bahrain', '🇧🇭'),
    ('Bangladesh', '🇧🇩'),
    ('Barbados', '🇧🇧'),
    ('Belarus', '🇧🇾'),
    ('Belgium', '🇧🇪'),
    ('Belize', '🇧🇿'),
    ('Benin', '🇧🇯'),
    ('Bermuda', '🇧🇲'),
    ('Bhutan', '🇧🇹'),
    ('Bolivia', '🇧🇴'),
    ('Bosnia and Herzegovina', '🇧🇦'),
    ('Botswana', '🇧🇼'),
    ('Bouvet Island', '🇧🇻'),
    ('Brazil', '🇧🇷'),
    ('British Indian Ocean Territory', '🇮🇴'),
    ('British Virgin Islands', '🇻🇬'),
    ('Brunei', '🇧🇳'),
    ('Bulgaria', '🇧🇬'),
    ('Burkina Faso', '🇧🇫'),
    ('Burundi', '🇧🇮'),
    ('Cabo Verde', '🇨🇻'),
    ('Cambodia', '🇰🇭'),
    ('Cameroon', '🇨🇲'),
    ('Canada', '🇨🇦'),
    ('Caribbean Netherlands', '🇧🇶'),
    ('Cayman Islands', '🇰🇾'),
    ('Central African Republic', '🇨🇫'),
    ('Chad', '🇹🇩'),
    ('Chile', '🇨🇱'),
    ('China', '🇨🇳'),
    ('Christmas Island', '🇨🇽'),
    ('Cocos (Keeling) Islands', '🇨🇨'),
    ('Colombia', '🇨🇴'),
    ('Comoros', '🇰🇲'),
    ('Cook Islands', '🇨🇰'),
    ('Costa Rica', '🇨🇷'),
    ('Croatia', '🇭🇷'),
    ('Cuba', '🇨🇺'),
    ('Curaçao', '🇨🇼'),
    ('Cyprus', '🇨🇾'),
    ('Czech Republic', '🇨🇿'),
    ('Democratic Republic of the Congo', '🇨🇩'),
    ('Denmark', '🇩🇰'),
    ('Djibouti', '🇩🇯'),
    ('Dominica', '🇩🇲'),
    ('Dominican Republic', '🇩🇴'),
    ('Ecuador', '🇪🇨'),
    ('Egypt', '🇪🇬'),
    ('El Salvador', '🇸🇻'),
    ('England', '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f'),
    ('Equatorial Guinea', '🇬🇶'),
    ('Eritrea', '🇪🇷'),
    ('Estonia', '🇪🇪'),
    ('Eswatini', '🇸🇿'),
    ('Ethiopia', '🇪🇹'),
    ('Falkland Islands', '🇫🇰'),
    ('Faroe Islands', '🇫🇴'),
    ('Fiji', '🇫🇯'),
    ('Finland', '🇫🇮'),
    ('France', '🇫🇷'),
    ('French Guiana', '🇬🇫'),
    ('French Polynesia', '🇵🇫'),
    ('French Southern Territories', '🇹🇫'),
    ('Gabon', '🇬🇦'),
    ('Gambia', '🇬🇲'),
    ('Georgia', '🇬🇪'),
    ('Germany', '🇩🇪'),
    ('Ghana', '🇬🇭'),
    ('Gibraltar', '🇬🇮'),
    ('Greece', '🇬🇷'),
    ('Greenland', '🇬🇱'),
    ('Grenada', '🇬🇩'),
    ('Guadeloupe', '🇬🇵'),
    ('Guam', '🇬🇺'),
    ('Guatemala', '🇬🇹'),
    ('Guernsey', '🇬🇬'),
    ('Guinea', '🇬🇳'),
    ('Guinea-Bissau', '🇬🇼'),
    ('Guyana', '🇬🇾'),
    ('Haiti', '🇭🇹'),
    ('Heard Island and McDonald Islands', '🇭🇲'),
    ('Honduras', '🇭🇳'),
    ('Hong Kong', '🇭🇰'),
    ('Hungary', '🇭🇺'),
    ('Iceland', '🇮🇸'),
    ('India', '🇮🇳'),
    ('Indonesia', '🇮🇩'),
    ('Iran', '🇮🇷'),
    ('Iraq', '🇮🇶'),
    ('Ireland', '🇮🇪'),
    ('Isle of Man', '🇮🇲'),
    ('Israel', '🇮🇱'),
    ('Italy', '🇮🇹'),
    ('Ivory Coast', '🇨🇮'),
    ('Jamaica', '🇯🇲'),
    ('Japan', '🇯🇵'),
    ('Jersey', '🇯🇪'),
    ('Jordan', '🇯🇴'),
    ('Kazakhstan', '🇰🇿'),
    ('Kenya', '🇰🇪'),
    ('Kiribati', '🇰🇮'),
    ('Kosovo', '🇽🇰'),
    ('Kuwait', '🇰🇼'),
    ('Kyrgyzstan', '🇰🇬'),
    ('Laos', '🇱🇦'),
    ('Latvia', '🇱🇻'),
    ('Lebanon', '🇱🇧'),
    ('Lesotho', '🇱🇸'),
    ('Liberia', '🇱🇷'),
    ('Libya', '🇱🇾'),
    ('Liechtenstein', '🇱🇮'),
    ('Lithuania', '🇱🇹'),
    ('Luxembourg', '🇱🇺'),
    ('Macao', '🇲🇴'),
    ('Madagascar', '🇲🇬'),
    ('Malawi', '🇲🇼'),
    ('Malaysia', '🇲🇾'),
    ('Maldives', '🇲🇻'),
    ('Mali', '🇲🇱'),
    ('Malta', '🇲🇹'),
    ('Marshall Islands', '🇲🇭'),
    ('Martinique', '🇲🇶'),
    ('Mauritania', '🇲🇷'),
    ('Mauritius', '🇲🇺'),
    ('Mayotte', '🇾🇹'),
    ('Mexico', '🇲🇽'),
    ('Micronesia', '🇫🇲'),
    ('Moldova', '🇲🇩'),
    ('Monaco', '🇲🇨'),
    ('Mongolia', '🇲🇳'),
    ('Montenegro', '🇲🇪'),
    ('Montserrat', '🇲🇸'),
    ('Morocco', '🇲🇦'),
    ('Mozambique', '🇲🇿'),
    ('Myanmar', '🇲🇲'),
    ('Namibia', '🇳🇦'),
    ('Nauru', '🇳🇷'),
    ('Nepal', '🇳🇵'),
    ('Netherlands', '🇳🇱'),
    ('New Caledonia', '🇳🇨'),
    ('New Zealand', '🇳🇿'),
    ('Nicaragua', '🇳🇮'),
    ('Niger', '🇳🇪'),
    ('Nigeria', '🇳🇬'),
    ('Niue', '🇳🇺'),
    ('Norfolk Island', '🇳🇫'),
    ('North Korea', '🇰🇵'),
    ('North Macedonia', '🇲🇰'),
    ('Northern Mariana Islands', '🇲🇵'),
    ('Norway', '🇳🇴'),
    ('Oman', '🇴🇲'),
    ('Pakistan', '🇵🇰'),
    ('Palau', '🇵🇼'),
    ('Palestine', '🇵🇸'),
    ('Panama', '🇵🇦'),
    ('Papua New Guinea', '🇵🇬'),
    ('Paraguay', '🇵🇾'),
    ('Peru', '🇵🇪'),
    ('Philippines', '🇵🇭'),
    ('Pitcairn Islands', '🇵🇳'),
    ('Poland', '🇵🇱'),
    ('Portugal', '🇵🇹'),
    ('Puerto Rico', '🇵🇷'),
    ('Qatar', '🇶🇦'),
    ('Republic of the Congo', '🇨🇬'),
    ('Romania', '🇷🇴'),
    ('Russia', '🇷🇺'),
    ('Rwanda', '🇷🇼'),
    ('Réunion', '🇷🇪'),
    ('Saint Barthélemy', '🇧🇱'),
    ('Saint Helena', '🇸🇭'),
    ('Saint Kitts and Nevis', '🇰🇳'),
    ('Saint Lucia', '🇱🇨'),
    ('Saint Martin', '🇲🇫'),
    ('Saint Pierre and Miquelon', '🇵🇲'),
    ('Saint Vincent and the Grenadines', '🇻🇨'),
    ('Samoa', '🇼🇸'),
    ('San Marino', '🇸🇲'),
    ('Saudi Arabia', '🇸🇦'),
    ('Scotland', '🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f'),
    ('Senegal', '🇸🇳'),
    ('Serbia', '🇷🇸'),
    ('Seychelles', '🇸🇨'),
    ('Sierra Leone', '🇸🇱'),
    ('Singapore', '🇸🇬'),
    ('Sint Maarten', '🇸🇽'),
    ('Slovakia', '🇸🇰'),
    ('Slovenia', '🇸🇮'),
    ('Solomon Islands', '🇸🇧'),
    ('Somalia', '🇸🇴'),
    ('South Africa', '🇿🇦'),
    ('South Georgia and the South Sandwich Islands', '🇬🇸'),
    ('South Korea', '🇰🇷'),
    ('South Sudan', '🇸🇸'),
    ('Spain', '🇪🇸'),
    ('Sri Lanka', '🇱🇰'),
    ('Sudan', '🇸🇩'),
    ('Suriname', '🇸🇷'),
    ('Svalbard and Jan Mayen', '🇸🇯'),
    ('Sweden', '🇸🇪'),
    ('Switzerland', '🇨🇭'),
    ('Syria', '🇸🇾'),
    ('São Tomé and Príncipe', '🇸🇹'),
    ('Taiwan', '🇹🇼'),
    ('Tajikistan', '🇹🇯'),
    ('Tanzania', '🇹🇿'),
    ('Thailand', '🇹🇭'),
    ('Timor-Leste', '🇹🇱'),
    ('Togo', '🇹🇬'),
    ('Tokelau', '🇹🇰'),
    ('Tonga', '🇹🇴'),
    ('Trinidad and Tobago', '🇹🇹'),
    ('Tunisia', '🇹🇳'),
    ('Turkey', '🇹🇷'),
    ('Turkmenistan', '🇹🇲'),
    ('Turks and Caicos Islands', '🇹🇨'),
    ('Tuvalu', '🇹🇻'),
    ('U.S. Virgin Islands', '🇻🇮'),
    ('Uganda', '🇺🇬'),
    ('Ukraine', '🇺🇦'),
    ('United Arab Emirates', '🇦🇪'),
    ('United Kingdom', '🇬🇧'),
    ('United States', '🇺🇸'),
    ('United States Minor Outlying Islands', '🇺🇲'),
    ('Uruguay', '🇺🇾'),
    ('Uzbekistan', '🇺🇿'),
    ('Vanuatu', '🇻🇺'),
    ('Vatican City', '🇻🇦'),
    ('Venezuela', '🇻🇪'),
    ('Vietnam', '🇻🇳'),
    ('Wales', '🏴\U000e0067\U000e0062\U000e0077\U000e006c\U000e0073\U000e007f'),
    ('Wallis and Futuna', '🇼🇫'),
    ('Western Sahara', '🇪🇭'),
    ('Yemen', '🇾🇪'),
    ('Zambia', '🇿🇲'),
    ('Zimbabwe', '🇿🇼'),
    ('Åland Islands', '🇦🇽'),
]


# Historical empires / polities → modern successor countries (primary first).
# Picking an empire also links these country hubs on the event.
EMPIRES: list[tuple[str, str, list[str]]] = [
    ("Abbasid Caliphate", "🏛️", ["Iraq", "Iran", "Syria", "Egypt"]),
    ("Akkadian Empire", "🏛️", ["Iraq"]),
    ("Ancient Egypt", "🏛️", ["Egypt"]),
    ("Ancient Greece", "🏛️", ["Greece"]),
    ("Ancient Rome", "🏛️", ["Italy"]),
    ("Austrian Empire", "🏛️", ["Austria", "Hungary", "Czech Republic"]),
    ("Aztec Empire", "🏛️", ["Mexico"]),
    ("British Empire", "🏛️", ["United Kingdom"]),
    ("Byzantine Empire", "🏛️", ["Turkey", "Greece"]),
    ("Carthage", "🏛️", ["Tunisia"]),
    ("Dutch Empire", "🏛️", ["Netherlands"]),
    ("Frankish Empire", "🏛️", ["France", "Germany"]),
    ("French Empire", "🏛️", ["France"]),
    ("German Empire", "🏛️", ["Germany"]),
    ("Holy Roman Empire", "🏛️", ["Germany", "Austria", "Italy"]),
    ("Inca Empire", "🏛️", ["Peru", "Bolivia"]),
    ("Macedonian Empire", "🏛️", ["Greece"]),
    ("Mali Empire", "🏛️", ["Ghana"]),
    ("Mongol Empire", "🏛️", ["Mongolia", "China"]),
    ("Mughal Empire", "🏛️", ["India", "Pakistan", "Bangladesh"]),
    ("Ottoman Empire", "🏛️", ["Turkey", "Greece", "Syria", "Iraq", "Egypt"]),
    ("Persian Empire", "🏛️", ["Iran"]),
    ("Portuguese Empire", "🏛️", ["Portugal", "Brazil"]),
    ("Qing Empire", "🏛️", ["China"]),
    ("Roman Empire", "🏛️", ["Italy"]),
    ("Russian Empire", "🏛️", ["Russia"]),
    ("Safavid Empire", "🏛️", ["Iran"]),
    ("Spanish Empire", "🏛️", ["Spain", "Mexico", "Peru"]),
    ("Umayyad Caliphate", "🏛️", ["Syria", "Spain", "Egypt"]),
]

# Broad historical periods: (name, start_year, end_year)
# Years are signed integers: negative = BC, positive = AC/CE.
PERIODS: list[tuple[str, int, int]] = [
    ("Prehistory", -300000, -3000),
    ("Ancient Near East", -3500, -539),
    ("Ancient Egypt", -3100, -30),
    ("Classical Greece", -800, -146),
    ("Roman Republic", -509, -27),
    ("Roman Empire", -27, 476),
    ("Late Antiquity", 250, 750),
    ("Early Middle Ages", 500, 1000),
    ("High Middle Ages", 1000, 1300),
    ("Late Middle Ages", 1300, 1500),
    ("Renaissance", 1400, 1600),
    ("Age of Exploration", 1415, 1600),
    ("Reformation", 1517, 1648),
    ("Early Modern Period", 1500, 1800),
    ("Scientific Revolution", 1543, 1687),
    ("Age of Enlightenment", 1685, 1815),
    ("American Revolution", 1765, 1783),
    ("French Revolution", 1789, 1799),
    ("Napoleonic Era", 1799, 1815),
    ("Industrial Revolution", 1760, 1840),
    ("Victorian Era", 1837, 1901),
    ("German Unification", 1864, 1871),
    ("Meiji Period", 1868, 1912),
    ("Belle Époque", 1871, 1914),
    ("World War I", 1914, 1918),
    ("Interwar Period", 1918, 1939),
    ("World War II", 1939, 1945),
    ("Cold War", 1947, 1991),
    ("Decolonization", 1945, 1975),
    ("Post–Cold War", 1991, 2010),
    ("Contemporary History", 1991, 2100),
    ("Islamic Golden Age", 750, 1258),
    ("Tang Dynasty", 618, 907),
    ("Ming Dynasty", 1368, 1644),
    ("Qing Dynasty", 1644, 1912),
    ("Mughal Empire", 1526, 1857),
    ("Age of Absolutism", 1648, 1789),
    ("Baroque Period", 1600, 1750),
    ("Romantic Era", 1800, 1850),
    ("Modern Europe", 1789, 2100),
]

# Well-known figures / characters for history study
FIGURES: list[str] = [
    "Alexander the Great",
    "Cleopatra",
    "Julius Caesar",
    "Augustus",
    "Jesus of Nazareth",
    "Constantine the Great",
    "Attila the Hun",
    "Muhammad",
    "Charlemagne",
    "Genghis Khan",
    "Marco Polo",
    "Joan of Arc",
    "Leonardo da Vinci",
    "Michelangelo",
    "Martin Luther",
    "Elizabeth I",
    "William Shakespeare",
    "Galileo Galilei",
    "Isaac Newton",
    "Louis XIV",
    "Peter the Great",
    "Catherine the Great",
    "George Washington",
    "Thomas Jefferson",
    "Napoleon Bonaparte",
    "Duke of Wellington",
    "Simón Bolívar",
    "Abraham Lincoln",
    "Queen Victoria",
    "Otto von Bismarck",
    "Karl Marx",
    "Charles Darwin",
    "Florence Nightingale",
    "Sun Yat-sen",
    "Vladimir Lenin",
    "Joseph Stalin",
    "Adolf Hitler",
    "Winston Churchill",
    "Franklin D. Roosevelt",
    "Mahatma Gandhi",
    "Mao Zedong",
    "Albert Einstein",
    "Martin Luther King Jr.",
    "Nelson Mandela",
    "John F. Kennedy",
    "Margaret Thatcher",
    "Mikhail Gorbachev",
    "Confucius",
    "Socrates",
    "Plato",
    "Aristotle",
    "Hannibal",
    "Saladin",
    "Akbar",
    "Tokugawa Ieyasu",
    "Oda Nobunaga",
    "Hatshepsut",
    "Ramses II",
    "Cyrus the Great",
    "Ashoka",
    "Mansa Musa",
    "Suleiman the Magnificent",
    "Ivan the Terrible",
    "Henry VIII",
    "Marie Antoinette",
    "Robespierre",
    "Toussaint Louverture",
    "Harriet Tubman",
    "Frederick Douglass",
    "Rosa Parks",
    "Malcolm X",
    "Che Guevara",
    "Fidel Castro",
    "Ho Chi Minh",
    "Kim Il-sung",
    "Indira Gandhi",
    "Golda Meir",
    "Yasser Arafat",
    "Anwar Sadat",
    "Yitzhak Rabin",
]


def catalog_payload() -> dict:
    modern_names = {n for n, _ in COUNTRIES}
    empires = []
    for name, flag, modern in EMPIRES:
        # Only keep successors that exist in the modern country catalog
        linked = [m for m in modern if m in modern_names]
        empires.append({"name": name, "flag": flag, "modern": linked})
    return {
        "countries": [{"name": n, "flag": f} for n, f in COUNTRIES],
        "empires": empires,
        "periods": [
            {"name": n, "start_year": start, "end_year": end} for n, start, end in PERIODS
        ],
        "figures": [{"name": n} for n in FIGURES],
    }
